apiVersion: v1
kind: ConfigMap
metadata:
  name: insureai-config
  namespace: insureai
data:
  FRONTEND_ORIGIN: "http://insureai-dashboard.insureai.svc.cluster.local"
  LOG_LEVEL: "INFO"
  PYTHONUNBUFFERED: "1"
